bin: apply shfmt

diff --git a/bin/taskdir b/bin/taskdir
--- a/bin/taskdir
+++ b/bin/taskdir
@@ -26,8 +26,8 @@ set -eu
 OUTPUT=$(taskoutput "$@")
 
 if [ "$?" -eq 0 ]; then
-    dirname "$OUTPUT"
+	dirname "$OUTPUT"
 else
-    echo "cannot determine task directory"
-    exit 1
+	echo "cannot determine task directory"
+	exit 1
 fi
diff --git a/bin/taskopen b/bin/taskopen
--- a/bin/taskopen
+++ b/bin/taskopen
@@ -24,13 +24,13 @@
 set -eu
 
 xopen() {
-    if hash gnome-open 2> /dev/null; then
-        gnome-open "$@"
-    elif hash open 2> /dev/null; then
-        open "$@"
-    else
-        echo "open or gnome-open required" && exit 1
-    fi
+	if hash gnome-open 2>/dev/null; then
+		gnome-open "$@"
+	elif hash open 2>/dev/null; then
+		open "$@"
+	else
+		echo "open or gnome-open required" && exit 1
+	fi
 }
 
 xopen $(taskoutput "$@")
diff --git a/bin/taskstatus b/bin/taskstatus
--- a/bin/taskstatus
+++ b/bin/taskstatus
@@ -27,14 +27,14 @@ set -eu
 OUTPUT=$(taskoutput "$@")
 
 if [ $? -ne 0 ]; then
-    echo "cannot get task status"
-    exit 1
+	echo "cannot get task status"
+	exit 1
 fi
 
 if [ -e "$OUTPUT" ]; then
-    echo "DONE $OUTPUT"
-    exit 0
+	echo "DONE $OUTPUT"
+	exit 0
 else
-    echo "TODO $OUTPUT"
-    exit 1
+	echo "TODO $OUTPUT"
+	exit 1
 fi
diff --git a/bin/tasktree b/bin/tasktree
--- a/bin/tasktree
+++ b/bin/tasktree
@@ -24,13 +24,13 @@
 set -eu
 
 if [ "$#" -eq 0 ]; then
-    tree -ash "$(taskhome)"
+	tree -ash "$(taskhome)"
 else
-    DIR=$(taskdir "$@")
-    if [ "$?" -eq 0 ]; then
-        tree -sh "$DIR"
-    else
-        echo "cannot find directory for task, maybe add missing parameter (dummy value)"
-        exit 1
-    fi
+	DIR=$(taskdir "$@")
+	if [ "$?" -eq 0 ]; then
+		tree -sh "$DIR"
+	else
+		echo "cannot find directory for task, maybe add missing parameter (dummy value)"
+		exit 1
+	fi
 fi
