taskrm: cover case of a single name

diff --git a/bin/taskrm b/bin/taskrm
--- a/bin/taskrm
+++ b/bin/taskrm
@@ -22,25 +22,38 @@
 #
 # @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
 
-set -eu
+set -e
 
 if [ "$#" -eq 0 ]; then
-    >&2 echo "usage: taskrm TASKNAME [--op1 abc, --op2, ...] [TASKNAME, TASKNAME, ...]"
+    echo >&2 "usage: taskrm TASKNAME [--op1 abc, --op2, ...] [TASKNAME, TASKNAME, ...]"
     exit 0
 fi
 
+# Assuming: single task name.
+if [ "$#" -eq 1 ]; then
+    OUTPUT=$(taskoutput "$1")
+    if [ "$?" -ne 0 ]; then
+        printf >&2 "cannot determine task output [%d]\n" $?
+        exit 1
+    else
+        rm -vf "$OUTPUT"
+    fi
+    exit 0
+fi
+
+# Assuming: task with flag or multiple tasks.
 case $2 in
 *--*)
     # We have some flag, so args contain task name and args.
     OUTPUT=$(taskoutput "$@")
     if [ "$?" -ne 0 ]; then
-        >&2 printf "cannot determine task output [%d]\n" $?
+        printf >&2 "cannot determine task output [%d]\n" $?
         exit 1
     else
         if [ -f "$OUTPUT" ]; then
             rm -vf "$OUTPUT"
         else
-            >&2 echo "[ok] nothing to remove"
+            echo >&2 "[ok] nothing to remove"
         fi
         exit 0
     fi
@@ -50,7 +63,7 @@ case $2 in
     for name in "$@"; do
         OUTPUT=$(taskoutput "$name")
         if [ "$?" -ne 0 ]; then
-            >&2 printf "cannot determine task output [%d]\n" $?
+            printf >&2 "cannot determine task output [%d]\n" $?
             exit 1
         else
             rm -vf "$OUTPUT"
