bin: towards more robust scripts

diff --git a/bin/taskrm b/bin/taskrm
--- a/bin/taskrm
+++ b/bin/taskrm
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/bin/sh
+# coding: utf-8
 
 #  Copyright 2015 by Leipzig University Library, http://ub.uni-leipzig.de
 #                 by The Finc Authors, http://finc.info
@@ -23,6 +24,12 @@
 #
 
 set -eu
-set -o pipefail
 
-rm -v $(taskoutput "$@" 2> /dev/null|tail -1)
+OUTPUT=$(taskoutput "$@")
+
+if [[ "$?" -ne 0 ]]; then
+    echo "cannot determine task output"
+    exit 1
+else
+    rm -v "$OUTPUT"
+fi
diff --git a/bin/taskstatus b/bin/taskstatus
--- a/bin/taskstatus
+++ b/bin/taskstatus
@@ -25,17 +25,17 @@
 # Display, whether a task is done or not.
 set -eu
 
-OUTPUT=$(taskoutput "$@" 2> /dev/null)
+OUTPUT=$(taskoutput "$@")
 
 if [ $? -ne 0 ]; then
-    echo "Usage: taskstatus TASKNAME"
+    echo "cannot get task status"
     exit 1
 fi
 
-if [ ! -e "$OUTPUT" ]; then
-    echo "TODO $OUTPUT"
-    exit 1
-else
+if [ -e "$OUTPUT" ]; then
     echo "DONE $OUTPUT"
     exit 0
+else
+    echo "TODO $OUTPUT"
+    exit 1
 fi
