bin: do not run tree, if task output needs parameters

diff --git a/bin/taskdir b/bin/taskdir
--- a/bin/taskdir
+++ b/bin/taskdir
@@ -23,4 +23,10 @@
 #
 
 set -eu
-dirname $(taskoutput "$@")
+OUTPUT=$(taskoutput "$@")
+if [ "$?" -eq 0 ]; then
+    dirname "$OUTPUT"
+else
+    echo "cannot determine task output"
+    exit 1
+fi
diff --git a/bin/tasktree b/bin/tasktree
--- a/bin/tasktree
+++ b/bin/tasktree
@@ -24,8 +24,14 @@
 
 set -eu
 
-if [ $# -eq 0 ]; then
-    tree -sh $(taskhome)
+if [ "$#" -eq 0 ]; then
+    tree -sh "$(taskhome)"
 else
-    tree -sh $(taskdir "$@")
+    DIR=$(taskdir "$@")
+    if [ "$?" -eq 0 ]; then
+        tree -sh "$DIR"
+    else
+        echo "cannot find directory for task, maybe add missing parameter (dummy value)"
+        exit 1
+    fi
 fi
