filterline: check, if args are files

diff --git a/siskin/assets/filterline b/siskin/assets/filterline
--- a/siskin/assets/filterline
+++ b/siskin/assets/filterline
@@ -15,6 +15,9 @@ if [ "$#" -ne 2 ]; then
     exit 1
 fi
 
+[ ! -f "$1" ] && echo "file not found: $1" && exit 1
+[ ! -f "$2" ] && echo "file not found: $2" && exit 1
+
 LIST="$1" LC_ALL=C awk '
   function nextline() {
     if ((getline n < list) <=0) exit
